# R8 rules for the Shell (:app).
#
# Module entry points are NOT kept here. Each module's own keep rule is generated by
# the `omnideck.module` convention plugin and travels with the module as a consumer
# rule, so a module added later needs no edit to this file (goal G1).

# Reflectively loaded by BundledModuleProvider when a module has no generated factory —
# a split installed after this APK was built (ADR-010). Its own consumer rule keeps the
# class; this keeps the no-argument constructor reachable through reflection.
-keepclassmembers class * implements com.omnideck.sdk.OmniModule {
    public <init>();
}

# kotlinx.serialization: the manifest and every @Serializable payload crossing the
# module boundary are decoded reflectively through generated serializers.
-keepattributes *Annotation*, InnerClasses
-dontnote kotlinx.serialization.**
-keepclassmembers @kotlinx.serialization.Serializable class * {
    *** Companion;
    *** INSTANCE;
    kotlinx.serialization.KSerializer serializer(...);
}

# Line numbers in a stack trace are what make module crash attribution actionable
# (QA-6). Without SourceFile the mapping file cannot restore them.
-keepattributes SourceFile, LineNumberTable
-renamesourcefileattribute SourceFile
