package com.omnideck.ksp

import com.google.devtools.ksp.KspExperimental
import com.google.devtools.ksp.getConstructors
import com.google.devtools.ksp.getVisibility
import com.google.devtools.ksp.isAbstract
import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.ClassKind
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.Visibility

/**
 * Generates the static module registry of architecture.md §7.2 (OD-202).
 *
 * It runs in two roles, decided by the `omnideck.aggregateModules` KSP argument that
 * the `omnideck.android.application` convention plugin sets:
 *
 *  - **In a module** — finds `ModuleEntryPoint`, checks it is a public class with a
 *    public no-arg constructor implementing `OmniModule`, and emits a tiny factory
 *    object into the well-known package [AGGREGATION_PACKAGE].
 *  - **In the Shell** — enumerates every factory object other modules put in that
 *    package (they are on the Shell's compile classpath, because the application
 *    plugin wires each bundled module in) and emits `GeneratedModuleRegistry`, a map
 *    from module id to a direct constructor call.
 *
 * The two-stage shape is what keeps goal G1 intact: neither half names a module, so
 * adding one is still nothing but a new directory.
 *
 * Why bother, when `Class.forName` already works? Two reasons, both about failure
 * timing. Reflection on the startup path costs a class-name lookup per bundled module
 * before the first frame; and a malformed entry point — a private constructor, a
 * missing interface, a typo'd name — currently fails at *load* time on a device, in
 * release builds only, after R8 has stripped the class. Here it fails at compile time
 * with a message that names the problem.
 */
class ModuleEntryPointProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
    private val aggregating: Boolean,
) : SymbolProcessor {

    private var done = false

    override fun process(resolver: Resolver): List<KSAnnotated> {
        // KSP calls process() once per round; everything here is resolvable in the
        // first, and generating again in a later round would duplicate the file.
        if (done) return emptyList()
        done = true

        if (aggregating) aggregate(resolver) else emitFactory(resolver)
        return emptyList()
    }

    // -- module side --------------------------------------------------------

    private fun emitFactory(resolver: Resolver) {
        val entryPoint = resolver.getAllFiles()
            .flatMap { it.declarations }
            .filterIsInstance<KSClassDeclaration>()
            .firstOrNull { it.simpleName.asString() == ENTRY_POINT_NAME }
            ?: return

        if (!entryPoint.validate(logger)) return

        val moduleId = entryPoint.packageName.asString()
        val qualifiedName = entryPoint.qualifiedName?.asString() ?: return

        codeGenerator.createNewFile(
            dependencies = Dependencies(aggregating = false, entryPoint.containingFile!!),
            packageName = AGGREGATION_PACKAGE,
            fileName = factoryName(moduleId),
        ).bufferedWriter().use { out ->
            out.write(
                """
                |// Generated by :tools:module-processor (OD-202). DO NOT EDIT.
                |package $AGGREGATION_PACKAGE
                |
                |import com.omnideck.sdk.OmniModule
                |
                |/**
                | * Compile-time factory for the `$moduleId` module, so the Shell can construct
                | * it without reflection (architecture.md §7.2).
                | */
                |public object ${factoryName(moduleId)} {
                |    public const val ID: String = "$moduleId"
                |
                |    public fun create(): OmniModule = $qualifiedName()
                |}
                |
                """.trimMargin(),
            )
        }
    }

    /**
     * The checks that used to be a device-only, release-only failure.
     *
     * Each one corresponds to a real way `BundledModuleProvider.load` blows up: a
     * missing interface becomes a `ClassCastException`, a private or argument-taking
     * constructor becomes a `NoSuchMethodException`, and neither says which module.
     */
    private fun KSClassDeclaration.validate(logger: KSPLogger): Boolean {
        val problems = buildList {
            if (classKind != ClassKind.CLASS || isAbstract()) {
                add("must be a concrete class")
            }
            if (getVisibility() != Visibility.PUBLIC) {
                add("must be public — the Shell instantiates it from outside its package")
            }
            if (packageName.asString() != containingFile?.packageName?.asString()) {
                add("must live in the module's own namespace")
            }
            if (getConstructors().none { it.parameters.isEmpty() && it.getVisibility() == Visibility.PUBLIC }) {
                add("must have a public no-argument constructor")
            }
            if (superTypes.none { it.resolve().declaration.qualifiedName?.asString() == OMNI_MODULE }) {
                add("must implement $OMNI_MODULE")
            }
        }

        problems.forEach { logger.error("$ENTRY_POINT_NAME $it.", this) }
        return problems.isEmpty()
    }

    // -- Shell side ---------------------------------------------------------

    @OptIn(KspExperimental::class)
    private fun aggregate(resolver: Resolver) {
        val factories = resolver.getDeclarationsFromPackage(AGGREGATION_PACKAGE)
            .filterIsInstance<KSClassDeclaration>()
            .filter { it.classKind == ClassKind.OBJECT }
            .mapNotNull { it.qualifiedName?.asString() }
            .sorted()
            .toList()

        logger.info("OmniDeck: generating a static registry for ${factories.size} bundled module(s)")

        // Imported rather than fully qualified inline: a generated line over 120
        // columns trips the repo's own formatting gate, and generated code that
        // cannot pass the gates it ships beside is a trap for the next person.
        val imports = factories.joinToString(separator = "\n") { "|import $it" }
        val entries = factories.joinToString(separator = "\n") { factory ->
            val simpleName = factory.substringAfterLast('.')
            "|        $simpleName.ID to { $simpleName.create() },"
        }

        codeGenerator.createNewFile(
            // No source file to attribute this to: it is derived from the compile
            // classpath, which is what `aggregating = true` means to KSP.
            dependencies = Dependencies(aggregating = true),
            packageName = REGISTRY_PACKAGE,
            fileName = REGISTRY_NAME,
        ).bufferedWriter().use { out ->
            out.write(
                """
                |// Generated by :tools:module-processor (OD-202). DO NOT EDIT.
                |package $REGISTRY_PACKAGE
                |
                |import com.omnideck.sdk.OmniModule
                $imports
                |
                |/**
                | * Every module compiled into the base APK, as a direct constructor call.
                | *
                | * The Shell hands this to the kernel's bundled provider so that starting a
                | * bundled module involves no class-name lookup (architecture.md §7.2).
                | * Modules delivered as splits are not here — their code does not exist at
                | * the time this is generated — and fall back to reflection.
                | */
                |public object $REGISTRY_NAME {
                |    public val factories: Map<String, () -> OmniModule> = mapOf(
                $entries
                |    )
                |}
                |
                """.trimMargin(),
            )
        }
    }

    private fun factoryName(moduleId: String) = "Entry_" + moduleId.replace('.', '_')

    private companion object {
        const val ENTRY_POINT_NAME = "ModuleEntryPoint"
        const val OMNI_MODULE = "com.omnideck.sdk.OmniModule"

        /**
         * Well-known package the two halves meet in. Nothing hand-written ever lives
         * here — it exists so the Shell can find factories without being told what
         * modules exist.
         */
        const val AGGREGATION_PACKAGE = "com.omnideck.generated.modules"
        const val REGISTRY_PACKAGE = "com.omnideck.generated"
        const val REGISTRY_NAME = "GeneratedModuleRegistry"
    }
}

class ModuleEntryPointProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor = ModuleEntryPointProcessor(
        codeGenerator = environment.codeGenerator,
        logger = environment.logger,
        aggregating = environment.options["omnideck.aggregateModules"].toBoolean(),
    )
}
